/* Copyright IBM Corp. 2017 */
import { ReactProvider } from '@acoustic-content-sdk/react-api';

import { ACOUSTIC_PROVIDER_REDUX_AUTH_STATUS } from './auth.status.module';
import { ACOUSTIC_PROVIDER_REDUX_DELIVERY_CONTENT_RESOLVER } from './content.module';
import { ACOUSTIC_PROVIDER_REDUX_FETCH_TEXT } from './fetch.text.module';
import { ACOUSTIC_PROVIDER_REDUX_HANDLEBARS_RESOLVER } from './handlebars.module';
import { ACOUSTIC_PROVIDER_REDUX_INLINE_EDIT_SELECTION_PROVIDER } from './inline.edit.module';
import { ACOUSTIC_PROVIDER_REDUX_DELIVERY_LAYOUT_MAPPING_RESOLVER } from './layout.mapping.module';
import { ACOUSTIC_PROVIDER_REDUX_DELIVERY_LAYOUT_RESOLVER } from './layout.module';
import { ACOUSTIC_PROVIDER_REDUX_DELIVERY_PAGE_RESOLVER } from './page.module';
import { ACOUSTIC_PROVIDER_REDUX_DELIVERY_SITE_RESOLVER } from './site.module';
import { ACOUSTIC_PROVIDER_REDUX_DELIVERY_TYPE_RESOLVER } from './type.module';
import { ACOUSTIC_PROVIDER_REDUX_URL_CONFIG } from './url.config.module';
import { ACOUSTIC_PROVIDER_REDUX_ACOUSTIC_CONFIG } from './wch.config.module';

/**
 * Exposes all providers for the redux feature
 */
export const ACOUSTIC_PROVIDERS_REDUX: Array<ReactProvider<any>> = [
  ACOUSTIC_PROVIDER_REDUX_DELIVERY_CONTENT_RESOLVER,
  ACOUSTIC_PROVIDER_REDUX_HANDLEBARS_RESOLVER,
  ACOUSTIC_PROVIDER_REDUX_DELIVERY_LAYOUT_MAPPING_RESOLVER,
  ACOUSTIC_PROVIDER_REDUX_DELIVERY_LAYOUT_RESOLVER,
  ACOUSTIC_PROVIDER_REDUX_DELIVERY_PAGE_RESOLVER,
  ACOUSTIC_PROVIDER_REDUX_DELIVERY_SITE_RESOLVER,
  ACOUSTIC_PROVIDER_REDUX_DELIVERY_TYPE_RESOLVER,
  ACOUSTIC_PROVIDER_REDUX_URL_CONFIG,
  ACOUSTIC_PROVIDER_REDUX_ACOUSTIC_CONFIG,
  ACOUSTIC_PROVIDER_REDUX_AUTH_STATUS,
  ACOUSTIC_PROVIDER_REDUX_FETCH_TEXT,
  ACOUSTIC_PROVIDER_REDUX_INLINE_EDIT_SELECTION_PROVIDER
];
